POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento2",
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/111eb1ae-a5a5-4efb-81f5-98d36677fbdf/attendees
Content-Type: application/json

{
  "name":"Luis Felipe",
  "email":"lfbmrj152@gmail.com"
}


### 
GET http://localhost:3333/events/111eb1ae-a5a5-4efb-81f5-98d36677fbdf

### 
GET http://localhost:3333/attendees/1/badge