POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento2",
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/df927a76-bd35-4bb3-aeef-ec16a320e66f/attendees
Content-Type: application/json

{
  "name":"Luis Felipe",
  "email":"lfbmrj152@gmail.com"
}


### 
GET http://localhost:3333/events/df927a76-bd35-4bb3-aeef-ec16a320e66f

### 
GET http://localhost:3333/attendees/1/badge

### 
GET http://localhost:3333/attendees/1/check-in

### 
GET http://localhost:3333/events/df927a76-bd35-4bb3-aeef-ec16a320e66f/attendees